runtime: custom
env: flex
env_variables:
  SKIP_PREFLIGHT_CHECK: true
  BUCKET_NAME: "stimson-gcs-ds-bucket"
  NODE_ENV: "production"
handlers:
  - url: /
    static_files: build/index.html
    require_matching_file: false
    upload: build/index.html
    secure: always
  - url: '/(.*)'
    static_files: "build/\\1"
    require_matching_file: false
    upload: 'build/.*'
    secure: always
