runtime: nodejs12
env: standard
env_variables:
  SKIP_PREFLIGHT_CHECK: true
  BUCKET_NAME: "stimson-gcs-ds-bucket"
  NODE_ENV: "production"
  REACT_APP_SCRAPPER_URL: "production"
  REACT_APP_CHANGEME: "Stimson123!"
#secure: always
